# Generated by Django 5.2.9 on 2025-12-18 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_temporal', models.DateTimeField(auto_now_add=True, verbose_name='Marca temporal')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('zona', models.CharField(choices=[('Sur', 'Sur'), ('Centro - Norte', 'Centro - Norte'), ('Norte', 'Norte'), ('Oeste', 'Oeste')], max_length=50, verbose_name='Zona')),
                ('operador', models.CharField(max_length=100, verbose_name='Operador')),
                ('apellido_nombre_interlocutor', models.CharField(max_length=200, verbose_name='Apellido y Nombre Interlocutor')),
                ('consulta', models.CharField(choices=[('Directa', 'Directa'), ('Indirecta', 'Indirecta')], max_length=20, verbose_name='Consulta')),
                ('telefono_interlocutor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono Interlocutor')),
                ('tipo_vinculo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Vínculo (Consulta Indirecta)')),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de la Consulta')),
                ('apellido_nombre_usuario', models.CharField(max_length=200, verbose_name='Apellido y Nombre Usuario')),
                ('dni', models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI')),
                ('fecha_nacimiento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha de Nacimiento')),
                ('edad', models.CharField(blank=True, max_length=20, null=True, verbose_name='Edad')),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro')], max_length=20, verbose_name='Sexo')),
                ('nacionalidad', models.CharField(default='Argentina', max_length=50, verbose_name='Nacionalidad')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('barrio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barrio')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('escolarizado', models.CharField(blank=True, choices=[('SI', 'Sí'), ('No', 'No')], max_length=5, null=True, verbose_name='Escolarizado')),
                ('etapa_escolar', models.CharField(blank=True, choices=[('Primaria Incompleta', 'Primaria Incompleta'), ('Primaria Completa', 'Primaria Completa'), ('Secundaria Incompleta', 'Secundaria Incompleta'), ('Secundaria Completa', 'Secundaria Completa'), ('Terciario/Universitario Incompleto', 'Terciario/Universitario Incompleto'), ('Terciario/Universitario Completo', 'Terciario/Universitario Completo')], max_length=100, null=True, verbose_name='Etapa Escolar')),
                ('obra_social', models.CharField(blank=True, choices=[('SI', 'Sí'), ('No', 'No')], max_length=5, null=True, verbose_name='Obra Social')),
                ('nombre_obra_social', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Obra Social')),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación')),
                ('apellido_nombre_referencia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido y Nombre Referencia Afectiva')),
                ('dni_referencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI Referencia Afectiva')),
                ('telefono_referencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono Referencia Afectiva')),
                ('tiempo_consumo', models.CharField(blank=True, choices=[('Menos de 1 año', 'Menos de 1 año'), ('De 1 años a 5', 'De 1 años a 5'), ('de 5 años a 10', 'De 5 años a 10'), ('Más de 10 años', 'Más de 10 años')], max_length=50, null=True, verbose_name='Tiempo de Consumo')),
                ('tipo_sustancia', models.TextField(blank=True, null=True, verbose_name='Tipo de Sustancia que Consume')),
                ('tratamiento_anterior', models.CharField(blank=True, choices=[('SI', 'Sí'), ('No', 'No')], max_length=5, null=True, verbose_name='Tratamiento Anterior')),
                ('tipo_tratamiento_anterior', models.TextField(blank=True, null=True, verbose_name='Tipo de Tratamiento Anterior')),
                ('efector_salud_referencia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Efector de Salud de Referencia')),
                ('riesgo_inminente', models.CharField(blank=True, choices=[('SI', 'Sí'), ('No', 'No')], max_length=5, null=True, verbose_name='Riesgo Inminente')),
                ('institucion_derivado', models.CharField(blank=True, max_length=200, null=True, verbose_name='Institución/Efector Derivado')),
                ('seguimiento', models.TextField(blank=True, null=True, verbose_name='Seguimiento')),
                ('situacion_social', models.CharField(blank=True, choices=[('Situación de Calle', 'Situación de Calle'), ('Infancia', 'Infancia'), ('Violencia', 'Violencia'), ('', 'Sin especificar')], max_length=50, null=True, verbose_name='Situación Social')),
                ('caracteristica_judicial', models.CharField(blank=True, choices=[('Judicializado', 'Judicializado'), ('', 'Sin especificar')], max_length=50, null=True, verbose_name='Característica Judicial')),
                ('intervencion_propuesta', models.TextField(blank=True, null=True, verbose_name='Intervención Propuesta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha', '-marca_temporal'],
            },
        ),
    ]
