# Generated by Django 5.2.9 on 2025-12-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='riesgo_inminente',
            field=models.CharField(blank=True, choices=[('Emergencia', 'Emergencia'), ('Urgencia', 'Urgencia'), ('Ninguno', 'Ninguno')], max_length=20, null=True, verbose_name='Riesgo Inminente'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='zona',
            field=models.CharField(choices=[('Centro - Norte', 'Centro - Norte'), ('Sur', 'Sur')], max_length=50, verbose_name='Zona'),
        ),
    ]
