# Generated by Django 5.2.9 on 2025-12-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_consulta_riesgo_inminente_alter_consulta_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='seguimiento',
            field=models.CharField(blank=True, choices=[('24hs', '24hs'), ('48hs', '48hs')], max_length=10, null=True, verbose_name='Seguimiento'),
        ),
    ]
