# Generated by Django 5.2.9 on 2025-12-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_alter_consulta_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='situacion_social',
            field=models.TextField(blank=True, null=True, verbose_name='Situación Social'),
        ),
    ]
