# Generated by Django 5.2.9 on 2025-12-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_alter_consulta_situacion_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='caracteristica_judicial',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Característica Judicial'),
        ),
    ]
