# Generated by Django 5.2.9 on 2025-12-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_alter_consulta_caracteristica_judicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro'), ('No corresponde', 'No corresponde'), ('No corresponde al tipo de llamada', 'No corresponde al tipo de llamada')], max_length=50, verbose_name='Sexo'),
        ),
    ]
